name: "build"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      # Note: this would only work if Cargo is included in the Nix shell
      - name: build
        run: |
          nix-build ./web/default.nix
          nix-build ./display/nix/default.nix
          nix-build ./display/nix/musl.nix
